service: note-express-api

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: ap-southeast-1
environment:
  NOTES_TABLE: ${env:NOTES_TABLE}
  STRIPE_SECRET_KEY: ${env:STRIPE_SECRET_KEY}
iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:DescribeTable
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
      - lambda: InvokeFunction
    Resource:
      - arn:aws:dynamodb:ap-southeast-1:280639150158:table/notes
      - arn:aws:lambda:ap-southeast-1:*:*
resources:
  - ${file(resources/api-gateway-errors.yml)}
functions:
  app:
    handler: dist/index.handler
    events:
      - http:
          path: notes
          method: get
          cors: true
          authorizer: aws_iam
      - http:
          path: notes
          method: post
          cors: true
          authorizer: aws_iam
      - http:
          path: notes/{id}
          method: get
          cors: true
          authorizer: aws_iam